networks:
    dev-shared:
        external: true

services:
    auth-api:
        container_name: auth-api
        build: ./
        ports:
            - "0.0.0.0:3000:3000"
        command: npm run dev
        env_file:
            - .env
        environment:
            - NODE_OPTIONS=--experimental-vm-modules
        networks:
            - dev-shared
        volumes:
            - ./:/app
            - /app/node_modules